### ISSUE TITLE
Constants missing analog stick buttons

### ISSUE THREAD

**Issue by davedoesdev** [torch2424/responsive-gamepad#21]
buttons[10] | Left stick pressed button
-- | --
buttons[11] | Right stick pressed button

Great library by the way

**Comment by torch2424** [comment]
Hello! Oh nice! Thank you so much for making these changes! Once I get off of of work, I'll go ahead, test these out, improve the demo site with the changes, and merge these in 😄

**Comment by davedoesdev** [comment]
Sure, thanks for writing this library

**Comment by torch2424** [comment]
You are welcome! Merged #22 which closes this 😄

**Comment by torch2424** [comment]
Also, @davedoesdev Deployed both of your PRs under version `1.2.0` 😄
